version: '3'

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - celery
      - redis

  db:
    image: postgres:15.3-alpine
    restart: always
    container_name: db
    environment:
      - POSTGRES_NAME=p14_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - '5432'

  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379

  celery:
    build: .
    command: celery -A P14RestProject worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
volumes:
  pg_data:
  redis_data:
